apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: gateways-canary
spec:
  profile: empty
  components:
    ingressGateways:
    - name: istio-ingressgateway-test
      namespace: istio-ingress
      enabled: true
      label:
        # Set a unique label for the gateway. This is required to ensure Gateways
        # can select this workload
        istio: ingressgateway
      k8s:
        service:
          type: ClusterIP
  values:
    gateways:
      istio-ingressgateway:
        # Enable gateway injection
        injectionTemplate: gateway
