apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: web-api-dr
spec:
  host: web-api.istioinaction.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  