apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: purchase-history-strict
  namespace: istioinaction
spec:
  selector:
    matchLabels:
      app: purchase-history
  mtls:
    mode: STRICT
