apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: default
spec:
  egress:
  - hosts:
    - "./*"    
    - "istio-system/*"
    - "istio-ingress/*"
    - "recommendation-ns/*"
    port:
      number: 8080
      protocol: HTTP
      name: egresshttp