apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: control-plane-install
  namespace: istio-system
spec:
  profile: minimal
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: cluster1
      network: network1
